/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingAboutusRouteImport } from './routes/_marketing/aboutus'
import { Route as MarketingContactSupportRouteImport } from './routes/_marketing/contact-support'
import { Route as MarketingDemoRouteImport } from './routes/_marketing/demo'
import { Route as MarketingFaqRouteImport } from './routes/_marketing/faq'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingPrivacyPolicyRouteImport } from './routes/_marketing/privacy-policy'
import { Route as MarketingProductRouteImport } from './routes/_marketing/product'
import { Route as MarketingSolutionsRouteImport } from './routes/_marketing/solutions'
import { Route as MarketingTermsOfServiceRouteImport } from './routes/_marketing/terms-of-service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAboutusRoute = MarketingAboutusRouteImport.update({
  id: '/aboutus',
  path: '/aboutus',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactSupportRoute = MarketingContactSupportRouteImport.update({
  id: '/contact-support',
  path: '/contact-support',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDemoRoute = MarketingDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqRoute = MarketingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyPolicyRoute = MarketingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingProductRoute = MarketingProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSolutionsRoute = MarketingSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTermsOfServiceRoute = MarketingTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutus': typeof MarketingAboutusRoute
  '/contact-support': typeof MarketingContactSupportRoute
  '/demo': typeof MarketingDemoRoute
  '/faq': typeof MarketingFaqRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/product': typeof MarketingProductRoute
  '/solutions': typeof MarketingSolutionsRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutus': typeof MarketingAboutusRoute
  '/contact-support': typeof MarketingContactSupportRoute
  '/demo': typeof MarketingDemoRoute
  '/faq': typeof MarketingFaqRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/product': typeof MarketingProductRoute
  '/solutions': typeof MarketingSolutionsRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/aboutus': typeof MarketingAboutusRoute
  '/_marketing/contact-support': typeof MarketingContactSupportRoute
  '/_marketing/demo': typeof MarketingDemoRoute
  '/_marketing/faq': typeof MarketingFaqRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/_marketing/product': typeof MarketingProductRoute
  '/_marketing/solutions': typeof MarketingSolutionsRoute
  '/_marketing/terms-of-service': typeof MarketingTermsOfServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutus'
    | '/contact-support'
    | '/demo'
    | '/faq'
    | '/pricing'
    | '/privacy-policy'
    | '/product'
    | '/solutions'
    | '/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutus'
    | '/contact-support'
    | '/demo'
    | '/faq'
    | '/pricing'
    | '/privacy-policy'
    | '/product'
    | '/solutions'
    | '/terms-of-service'
  id:
    | '__root__'
    | '/'
    | '/_marketing'
    | '/_marketing/aboutus'
    | '/_marketing/contact-support'
    | '/_marketing/demo'
    | '/_marketing/faq'
    | '/_marketing/pricing'
    | '/_marketing/privacy-policy'
    | '/_marketing/product'
    | '/_marketing/solutions'
    | '/_marketing/terms-of-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/aboutus': {
      id: '/_marketing/aboutus'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof MarketingAboutusRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact-support': {
      id: '/_marketing/contact-support'
      path: '/contact-support'
      fullPath: '/contact-support'
      preLoaderRoute: typeof MarketingContactSupportRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/demo': {
      id: '/_marketing/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof MarketingDemoRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faq': {
      id: '/_marketing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof MarketingFaqRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy-policy': {
      id: '/_marketing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof MarketingPrivacyPolicyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/product': {
      id: '/_marketing/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof MarketingProductRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/solutions': {
      id: '/_marketing/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof MarketingSolutionsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/terms-of-service': {
      id: '/_marketing/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof MarketingTermsOfServiceRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutusRoute: typeof MarketingAboutusRoute
  MarketingContactSupportRoute: typeof MarketingContactSupportRoute
  MarketingDemoRoute: typeof MarketingDemoRoute
  MarketingFaqRoute: typeof MarketingFaqRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingPrivacyPolicyRoute: typeof MarketingPrivacyPolicyRoute
  MarketingProductRoute: typeof MarketingProductRoute
  MarketingSolutionsRoute: typeof MarketingSolutionsRoute
  MarketingTermsOfServiceRoute: typeof MarketingTermsOfServiceRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutusRoute: MarketingAboutusRoute,
  MarketingContactSupportRoute: MarketingContactSupportRoute,
  MarketingDemoRoute: MarketingDemoRoute,
  MarketingFaqRoute: MarketingFaqRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingPrivacyPolicyRoute: MarketingPrivacyPolicyRoute,
  MarketingProductRoute: MarketingProductRoute,
  MarketingSolutionsRoute: MarketingSolutionsRoute,
  MarketingTermsOfServiceRoute: MarketingTermsOfServiceRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
