namespace Anamnys.Server.Data.Entities;

// Column subset of "Appointments" used by the provider calendar
// (design/specs/2026-10-05-provider-calendar-design.md) and read by the patient list,
// record and portal. Unmapped columns (series, session, hold, offering, connection, price,
// external event) are nullable or have defaults, so inserts through this entity work.
// "Slot" is generated by the database and deliberately left unmapped.
public class Appointment
{
    public Guid Id { get; set; }
    public Guid ProviderId { get; set; }
    public Guid PatientId { get; set; }
    public DateTimeOffset StartsAt { get; set; }
    public DateTimeOffset EndsAt { get; set; }
    public string Timezone { get; set; } = "";
    public string Modality { get; set; } = "";
    public string Status { get; set; } = "";
    public string CreatedBy { get; set; } = "provider";
    public DateTimeOffset? CancelledAt { get; set; }
    public string? CancelledBy { get; set; }
    public string? CancellationReason { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
}
