/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes/$noteId'
import { Route as AppPatientsIndexRouteImport } from './routes/_app/patients/index'
import { Route as AppPatientsNewRouteImport } from './routes/_app/patients/new'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppPatientsPatientIdIndexRouteImport } from './routes/_app/patients/$patientId/index'
import { Route as AppPatientsPatientIdLiveTranscribeRouteImport } from './routes/_app/patients/$patientId/live-transcribe'
import { Route as AppPatientsPatientIdNotesRouteImport } from './routes/_app/patients/$patientId/notes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsNewRoute = AppPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdIndexRoute =
  AppPatientsPatientIdIndexRouteImport.update({
    id: '/patients/$patientId/',
    path: '/patients/$patientId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdLiveTranscribeRoute =
  AppPatientsPatientIdLiveTranscribeRouteImport.update({
    id: '/patients/$patientId/live-transcribe',
    path: '/patients/$patientId/live-transcribe',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdNotesRoute =
  AppPatientsPatientIdNotesRouteImport.update({
    id: '/patients/$patientId/notes',
    path: '/patients/$patientId/notes',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/patients/': typeof AppPatientsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/patients/$patientId/live-transcribe': typeof AppPatientsPatientIdLiveTranscribeRoute
  '/patients/$patientId/notes': typeof AppPatientsPatientIdNotesRoute
  '/patients/$patientId/': typeof AppPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/patients': typeof AppPatientsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/patients/$patientId/live-transcribe': typeof AppPatientsPatientIdLiveTranscribeRoute
  '/patients/$patientId/notes': typeof AppPatientsPatientIdNotesRoute
  '/patients/$patientId': typeof AppPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/patients/new': typeof AppPatientsNewRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/patients/$patientId/live-transcribe': typeof AppPatientsPatientIdLiveTranscribeRoute
  '/_app/patients/$patientId/notes': typeof AppPatientsPatientIdNotesRoute
  '/_app/patients/$patientId/': typeof AppPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes/$noteId'
    | '/patients/new'
    | '/settings/account'
    | '/patients/'
    | '/settings/'
    | '/patients/$patientId/live-transcribe'
    | '/patients/$patientId/notes'
    | '/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes/$noteId'
    | '/patients/new'
    | '/settings/account'
    | '/patients'
    | '/settings'
    | '/patients/$patientId/live-transcribe'
    | '/patients/$patientId/notes'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/notes/$noteId'
    | '/_app/patients/new'
    | '/_app/settings/account'
    | '/_app/patients/'
    | '/_app/settings/'
    | '/_app/patients/$patientId/live-transcribe'
    | '/_app/patients/$patientId/notes'
    | '/_app/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/new': {
      id: '/_app/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AppPatientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/': {
      id: '/_app/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AppPatientsPatientIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/live-transcribe': {
      id: '/_app/patients/$patientId/live-transcribe'
      path: '/patients/$patientId/live-transcribe'
      fullPath: '/patients/$patientId/live-transcribe'
      preLoaderRoute: typeof AppPatientsPatientIdLiveTranscribeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/notes': {
      id: '/_app/patients/$patientId/notes'
      path: '/patients/$patientId/notes'
      fullPath: '/patients/$patientId/notes'
      preLoaderRoute: typeof AppPatientsPatientIdNotesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppPatientsNewRoute: typeof AppPatientsNewRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppPatientsPatientIdLiveTranscribeRoute: typeof AppPatientsPatientIdLiveTranscribeRoute
  AppPatientsPatientIdNotesRoute: typeof AppPatientsPatientIdNotesRoute
  AppPatientsPatientIdIndexRoute: typeof AppPatientsPatientIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppPatientsNewRoute: AppPatientsNewRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppPatientsPatientIdLiveTranscribeRoute:
    AppPatientsPatientIdLiveTranscribeRoute,
  AppPatientsPatientIdNotesRoute: AppPatientsPatientIdNotesRoute,
  AppPatientsPatientIdIndexRoute: AppPatientsPatientIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
